[package]
name = "dawn-ecs"
edition = "2021"

[dependencies]
dawn-util = { path = "../util" }
evenio = "0.6.0"
glam = "0.30.5"
log = "0.4.27"
anyhow = "1.0.99"
thiserror = "2.0.16"
web-time = "1.1.0"

[profile.release]
lto = true
opt-level = 3

[profile.dev]
lto = false
opt-level = 1