[package]
name = "dawn-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
dawn-util = { path = "../util" }
evenio = { version = "0.6.0", features = ["rayon"] }
glam = "0.30.5"
log = "0.4.27"

[profile.release]
lto = true
opt-level = 3

[profile.dev]
lto = false
opt-level = 1