[package]
name = "demo-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
yage2-core = { path = "../../crates/yage2-core" }
yage2-audio = { path = "../../crates/yage2-audio" }
log = "0.4.27"
evenio = "0.6.0"
glam="0.30.5"