use evenio::event::GlobalEvent;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MouseButton {
    Unknown(u32),

    Left,
    Right,
    Middle,
    Special(u8),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KeyCode {
    Unknown(u32, u32),

    // A-Z keys. Always uppercase.
    Latin(char),
    Cyrillic(char),
    Digit(u8),

    // Function keys
    BackSpace,
    Tab,
    Linefeed,
    Clear,
    Return,
    Pause,
    ScrollLock,
    SysReq,
    Escape,
    Delete,
    Home,
    Left,
    Up,
    Right,
    Down,
    PageUp,
    PageDown,
    End,
    Begin,
    WinL,
    WinR,
    App,
    Select,
    Print,
    Execute,
    Insert,
    Undo,
    Redo,
    Menu,
    Find,
    Cancel,
    Help,
    Break,
    ModeSwitch,
    NumLock,
    Function(u8),
    ShiftL,
    ShiftR,
    ControlL,
    ControlR,
    CapsLock,
    ShiftLock,
    MetaL,
    MetaR,
    AltL,
    AltR,
    SuperL,
    SuperR,
    HyperL,
    HyperR,
    Space,

    /* Printable keys */
    Exclam,
    Quotedbl,
    NumberSign,
    Dollar,
    Percent,
    Ampersand,
    Apostrophe,
    ParenLeft,
    ParenRight,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    Colon,
    Semicolon,
    Less,
    Equal,
    Greater,
    Question,
    At,
    BracketLeft,
    BracketRight,
    Backslash,
    AsciiCircum,
    Underscore,
    Grave,
    BraceLeft,
    BraceRight,
    Bar,
    Tilde,

    /* Keypad keys */
    KPSpace,
    KPTab,
    KPEnter,
    KPHome,
    KPLeft,
    KPUp,
    KPRight,
    KPDown,
    KPPageUp,
    KPPageDown,
    KPEnd,
    KPBegin,
    KPInsert,
    KPDelete,
    KPEqual,
    KPMultiply,
    KPAdd,
    KPSeparator,
    KPSubtract,
    KPDecimal,
    KPDivide,
    KPDigit(u8),
}

#[derive(GlobalEvent, Debug, Clone)]
pub enum InputEvent {
    KeyPress(KeyCode),
    KeyRelease(KeyCode),
    CharInput(char),
    MouseMove { x: f32, y: f32 },
    MouseScroll { delta_x: f32, delta_y: f32 },
    MouseButtonPress(MouseButton),
    MouseButtonRelease(MouseButton),
    Resize { width: u32, height: u32 },
}
