[package]
name = "yage2-sound"
version = "0.1.0"
edition = "2021"

[features]
default = ["cpal"]
cpal = ["dep:cpal"]

[dependencies]
yage2-core = { path = "../yage2-core" }
cpal = { version = "0.16.0", optional = true }
log = "0.4.27"
hound = "3.5.1"
rubato = "0.16.2"
i24 = "2.1.0"
