use crate::engine::event::{KeyCode, MouseButton};
use std::os::raw::{c_uchar, c_uint};
use x11::xlib::{Display, ShiftMask};

pub(crate) fn convert_key(display: *mut Display, keycode: c_uint, keystate: c_uint) -> KeyCode {
    /* Convert the X11 keycode to a keysym */
    let keysym = unsafe {
        x11::xlib::XkbKeycodeToKeysym(
            display,
            keycode as c_uchar,
            0,
            if keystate & ShiftMask != 0 { 1 } else { 0 },
        )
    };

    match keysym as c_uint {
        x11::keysym::XK_A => KeyCode::Latin('A'),
        x11::keysym::XK_B => KeyCode::Latin('B'),
        x11::keysym::XK_C => KeyCode::Latin('C'),
        x11::keysym::XK_D => KeyCode::Latin('D'),
        x11::keysym::XK_E => KeyCode::Latin('E'),
        x11::keysym::XK_F => KeyCode::Latin('F'),
        x11::keysym::XK_G => KeyCode::Latin('G'),
        x11::keysym::XK_H => KeyCode::Latin('H'),
        x11::keysym::XK_I => KeyCode::Latin('I'),
        x11::keysym::XK_J => KeyCode::Latin('J'),
        x11::keysym::XK_K => KeyCode::Latin('K'),
        x11::keysym::XK_L => KeyCode::Latin('L'),
        x11::keysym::XK_M => KeyCode::Latin('M'),
        x11::keysym::XK_N => KeyCode::Latin('N'),
        x11::keysym::XK_O => KeyCode::Latin('O'),
        x11::keysym::XK_P => KeyCode::Latin('P'),
        x11::keysym::XK_Q => KeyCode::Latin('Q'),
        x11::keysym::XK_R => KeyCode::Latin('R'),
        x11::keysym::XK_S => KeyCode::Latin('S'),
        x11::keysym::XK_T => KeyCode::Latin('T'),
        x11::keysym::XK_U => KeyCode::Latin('U'),
        x11::keysym::XK_V => KeyCode::Latin('V'),
        x11::keysym::XK_W => KeyCode::Latin('W'),
        x11::keysym::XK_X => KeyCode::Latin('X'),
        x11::keysym::XK_Y => KeyCode::Latin('Y'),
        x11::keysym::XK_Z => KeyCode::Latin('Z'),

        x11::keysym::XK_a => KeyCode::Latin('a'),
        x11::keysym::XK_b => KeyCode::Latin('b'),
        x11::keysym::XK_c => KeyCode::Latin('c'),
        x11::keysym::XK_d => KeyCode::Latin('d'),
        x11::keysym::XK_e => KeyCode::Latin('e'),
        x11::keysym::XK_f => KeyCode::Latin('f'),
        x11::keysym::XK_g => KeyCode::Latin('g'),
        x11::keysym::XK_h => KeyCode::Latin('h'),
        x11::keysym::XK_i => KeyCode::Latin('i'),
        x11::keysym::XK_j => KeyCode::Latin('j'),
        x11::keysym::XK_k => KeyCode::Latin('k'),
        x11::keysym::XK_l => KeyCode::Latin('l'),
        x11::keysym::XK_m => KeyCode::Latin('m'),
        x11::keysym::XK_n => KeyCode::Latin('n'),
        x11::keysym::XK_o => KeyCode::Latin('o'),
        x11::keysym::XK_p => KeyCode::Latin('p'),
        x11::keysym::XK_q => KeyCode::Latin('q'),
        x11::keysym::XK_r => KeyCode::Latin('r'),
        x11::keysym::XK_s => KeyCode::Latin('s'),
        x11::keysym::XK_t => KeyCode::Latin('t'),
        x11::keysym::XK_u => KeyCode::Latin('u'),
        x11::keysym::XK_v => KeyCode::Latin('v'),
        x11::keysym::XK_w => KeyCode::Latin('w'),
        x11::keysym::XK_x => KeyCode::Latin('x'),
        x11::keysym::XK_y => KeyCode::Latin('y'),
        x11::keysym::XK_z => KeyCode::Latin('z'),

        x11::keysym::XK_Cyrillic_A => KeyCode::Cyrillic('А'),
        x11::keysym::XK_Cyrillic_BE => KeyCode::Cyrillic('Б'),
        x11::keysym::XK_Cyrillic_VE => KeyCode::Cyrillic('В'),
        x11::keysym::XK_Cyrillic_GHE => KeyCode::Cyrillic('Г'),
        x11::keysym::XK_Cyrillic_DE => KeyCode::Cyrillic('Д'),
        x11::keysym::XK_Cyrillic_IE => KeyCode::Cyrillic('Е'),
        x11::keysym::XK_Cyrillic_ZHE => KeyCode::Cyrillic('Ж'),
        x11::keysym::XK_Cyrillic_ZE => KeyCode::Cyrillic('З'),
        x11::keysym::XK_Cyrillic_I => KeyCode::Cyrillic('И'),
        x11::keysym::XK_Cyrillic_SHORTI => KeyCode::Cyrillic('Й'),
        x11::keysym::XK_Cyrillic_KA => KeyCode::Cyrillic('К'),
        x11::keysym::XK_Cyrillic_EL => KeyCode::Cyrillic('Л'),
        x11::keysym::XK_Cyrillic_EM => KeyCode::Cyrillic('М'),
        x11::keysym::XK_Cyrillic_EN => KeyCode::Cyrillic('Н'),
        x11::keysym::XK_Cyrillic_O => KeyCode::Cyrillic('О'),
        x11::keysym::XK_Cyrillic_PE => KeyCode::Cyrillic('П'),
        x11::keysym::XK_Cyrillic_ER => KeyCode::Cyrillic('Р'),
        x11::keysym::XK_Cyrillic_ES => KeyCode::Cyrillic('С'),
        x11::keysym::XK_Cyrillic_TE => KeyCode::Cyrillic('Т'),
        x11::keysym::XK_Cyrillic_U => KeyCode::Cyrillic('У'),
        x11::keysym::XK_Cyrillic_EF => KeyCode::Cyrillic('Ф'),
        x11::keysym::XK_Cyrillic_HA => KeyCode::Cyrillic('Х'),
        x11::keysym::XK_Cyrillic_TSE => KeyCode::Cyrillic('Ц'),
        x11::keysym::XK_Cyrillic_CHE => KeyCode::Cyrillic('Ч'),
        x11::keysym::XK_Cyrillic_SHA => KeyCode::Cyrillic('Ш'),
        x11::keysym::XK_Cyrillic_SHCHA => KeyCode::Cyrillic('Щ'),
        x11::keysym::XK_Cyrillic_HARDSIGN => KeyCode::Cyrillic('Ъ'),
        x11::keysym::XK_Cyrillic_SOFTSIGN => KeyCode::Cyrillic('Ь'),
        x11::keysym::XK_Cyrillic_YERU => KeyCode::Cyrillic('Ы'),
        x11::keysym::XK_Cyrillic_YU => KeyCode::Cyrillic('Ю'),
        x11::keysym::XK_Cyrillic_YA => KeyCode::Cyrillic('Я'),

        x11::keysym::XK_Cyrillic_a => KeyCode::Cyrillic('а'),
        x11::keysym::XK_Cyrillic_be => KeyCode::Cyrillic('б'),
        x11::keysym::XK_Cyrillic_ve => KeyCode::Cyrillic('в'),
        x11::keysym::XK_Cyrillic_ghe => KeyCode::Cyrillic('г'),
        x11::keysym::XK_Cyrillic_de => KeyCode::Cyrillic('д'),
        x11::keysym::XK_Cyrillic_ie => KeyCode::Cyrillic('е'),
        x11::keysym::XK_Cyrillic_zhe => KeyCode::Cyrillic('ж'),
        x11::keysym::XK_Cyrillic_ze => KeyCode::Cyrillic('з'),
        x11::keysym::XK_Cyrillic_i => KeyCode::Cyrillic('и'),
        x11::keysym::XK_Cyrillic_shorti => KeyCode::Cyrillic('й'),
        x11::keysym::XK_Cyrillic_ka => KeyCode::Cyrillic('к'),
        x11::keysym::XK_Cyrillic_el => KeyCode::Cyrillic('л'),
        x11::keysym::XK_Cyrillic_em => KeyCode::Cyrillic('м'),
        x11::keysym::XK_Cyrillic_en => KeyCode::Cyrillic('н'),
        x11::keysym::XK_Cyrillic_o => KeyCode::Cyrillic('о'),
        x11::keysym::XK_Cyrillic_pe => KeyCode::Cyrillic('п'),
        x11::keysym::XK_Cyrillic_er => KeyCode::Cyrillic('р'),
        x11::keysym::XK_Cyrillic_es => KeyCode::Cyrillic('с'),
        x11::keysym::XK_Cyrillic_te => KeyCode::Cyrillic('т'),
        x11::keysym::XK_Cyrillic_u => KeyCode::Cyrillic('у'),
        x11::keysym::XK_Cyrillic_ef => KeyCode::Cyrillic('ф'),
        x11::keysym::XK_Cyrillic_ha => KeyCode::Cyrillic('х'),
        x11::keysym::XK_Cyrillic_tse => KeyCode::Cyrillic('ц'),
        x11::keysym::XK_Cyrillic_che => KeyCode::Cyrillic('ч'),
        x11::keysym::XK_Cyrillic_sha => KeyCode::Cyrillic('ш'),
        x11::keysym::XK_Cyrillic_shcha => KeyCode::Cyrillic('щ'),
        x11::keysym::XK_Cyrillic_hardsign => KeyCode::Cyrillic('ъ'),
        x11::keysym::XK_Cyrillic_softsign => KeyCode::Cyrillic('ь'),
        x11::keysym::XK_Cyrillic_yeru => KeyCode::Cyrillic('ы'),
        x11::keysym::XK_Cyrillic_yu => KeyCode::Cyrillic('ю'),
        x11::keysym::XK_Cyrillic_ya => KeyCode::Cyrillic('я'),

        x11::keysym::XK_0 => KeyCode::Digit(0),
        x11::keysym::XK_1 => KeyCode::Digit(1),
        x11::keysym::XK_2 => KeyCode::Digit(2),
        x11::keysym::XK_3 => KeyCode::Digit(3),
        x11::keysym::XK_4 => KeyCode::Digit(4),
        x11::keysym::XK_5 => KeyCode::Digit(5),
        x11::keysym::XK_6 => KeyCode::Digit(6),
        x11::keysym::XK_7 => KeyCode::Digit(7),
        x11::keysym::XK_8 => KeyCode::Digit(8),
        x11::keysym::XK_9 => KeyCode::Digit(9),

        /* Function keys */
        x11::keysym::XK_BackSpace => KeyCode::BackSpace,
        x11::keysym::XK_Tab => KeyCode::Tab,
        x11::keysym::XK_Linefeed => KeyCode::Linefeed,
        x11::keysym::XK_Clear => KeyCode::Clear,
        x11::keysym::XK_Return => KeyCode::Return,
        x11::keysym::XK_Pause => KeyCode::Pause,
        x11::keysym::XK_Scroll_Lock => KeyCode::ScrollLock,
        x11::keysym::XK_Sys_Req => KeyCode::SysReq,
        x11::keysym::XK_Escape => KeyCode::Escape,
        x11::keysym::XK_Delete => KeyCode::Delete,
        x11::keysym::XK_Home => KeyCode::Home,
        x11::keysym::XK_Left => KeyCode::Left,
        x11::keysym::XK_Up => KeyCode::Up,
        x11::keysym::XK_Right => KeyCode::Right,
        x11::keysym::XK_Down => KeyCode::Down,
        x11::keysym::XK_Prior => KeyCode::Prior,
        x11::keysym::XK_Page_Up => KeyCode::PageUp,
        x11::keysym::XK_Next => KeyCode::Next,
        x11::keysym::XK_Page_Down => KeyCode::PageDown,
        x11::keysym::XK_End => KeyCode::End,
        x11::keysym::XK_Begin => KeyCode::Begin,
        x11::keysym::XK_Win_L => KeyCode::WinL,
        x11::keysym::XK_Win_R => KeyCode::WinR,
        x11::keysym::XK_App => KeyCode::App,
        x11::keysym::XK_Select => KeyCode::Select,
        x11::keysym::XK_Print => KeyCode::Print,
        x11::keysym::XK_Execute => KeyCode::Execute,
        x11::keysym::XK_Insert => KeyCode::Insert,
        x11::keysym::XK_Undo => KeyCode::Undo,
        x11::keysym::XK_Redo => KeyCode::Redo,
        x11::keysym::XK_Menu => KeyCode::Menu,
        x11::keysym::XK_Find => KeyCode::Find,
        x11::keysym::XK_Cancel => KeyCode::Cancel,
        x11::keysym::XK_Help => KeyCode::Help,
        x11::keysym::XK_Break => KeyCode::Break,
        x11::keysym::XK_Mode_switch => KeyCode::ModeSwitch,
        x11::keysym::XK_script_switch => KeyCode::ScriptSwitch,
        x11::keysym::XK_Num_Lock => KeyCode::NumLock,
        x11::keysym::XK_Shift_L => KeyCode::ShiftL,
        x11::keysym::XK_Shift_R => KeyCode::ShiftR,
        x11::keysym::XK_Control_L => KeyCode::ControlL,
        x11::keysym::XK_Control_R => KeyCode::ControlR,
        x11::keysym::XK_Caps_Lock => KeyCode::CapsLock,
        x11::keysym::XK_Shift_Lock => KeyCode::ShiftLock,
        x11::keysym::XK_Meta_L => KeyCode::MetaL,
        x11::keysym::XK_Meta_R => KeyCode::MetaR,
        x11::keysym::XK_Alt_L => KeyCode::AltL,
        x11::keysym::XK_Alt_R => KeyCode::AltR,
        x11::keysym::XK_Super_L => KeyCode::SuperL,
        x11::keysym::XK_Super_R => KeyCode::SuperR,
        x11::keysym::XK_Hyper_L => KeyCode::HyperL,
        x11::keysym::XK_Hyper_R => KeyCode::HyperR,
        x11::keysym::XK_space => KeyCode::Space,

        x11::keysym::XK_F1 => KeyCode::Function(1),
        x11::keysym::XK_F2 => KeyCode::Function(2),
        x11::keysym::XK_F3 => KeyCode::Function(3),
        x11::keysym::XK_F4 => KeyCode::Function(4),
        x11::keysym::XK_F5 => KeyCode::Function(5),
        x11::keysym::XK_F6 => KeyCode::Function(6),
        x11::keysym::XK_F7 => KeyCode::Function(7),
        x11::keysym::XK_F8 => KeyCode::Function(8),
        x11::keysym::XK_F9 => KeyCode::Function(9),
        x11::keysym::XK_F10 => KeyCode::Function(10),
        x11::keysym::XK_F11 => KeyCode::Function(11),
        x11::keysym::XK_F12 => KeyCode::Function(12),
        x11::keysym::XK_F13 => KeyCode::Function(13),
        x11::keysym::XK_F14 => KeyCode::Function(14),
        x11::keysym::XK_F15 => KeyCode::Function(15),
        x11::keysym::XK_F16 => KeyCode::Function(16),
        x11::keysym::XK_F17 => KeyCode::Function(17),
        x11::keysym::XK_F18 => KeyCode::Function(18),
        x11::keysym::XK_F19 => KeyCode::Function(19),
        x11::keysym::XK_F20 => KeyCode::Function(20),
        x11::keysym::XK_F21 => KeyCode::Function(21),
        x11::keysym::XK_F22 => KeyCode::Function(22),
        x11::keysym::XK_F23 => KeyCode::Function(23),
        x11::keysym::XK_F24 => KeyCode::Function(24),
        x11::keysym::XK_F25 => KeyCode::Function(25),
        x11::keysym::XK_F26 => KeyCode::Function(26),
        x11::keysym::XK_F27 => KeyCode::Function(27),
        x11::keysym::XK_F28 => KeyCode::Function(28),
        x11::keysym::XK_F29 => KeyCode::Function(29),
        x11::keysym::XK_F30 => KeyCode::Function(30),
        x11::keysym::XK_F31 => KeyCode::Function(31),
        x11::keysym::XK_F32 => KeyCode::Function(32),
        x11::keysym::XK_F33 => KeyCode::Function(33),
        x11::keysym::XK_F34 => KeyCode::Function(34),
        x11::keysym::XK_F35 => KeyCode::Function(35),

        /* Printable keys */
        x11::keysym::XK_exclam => KeyCode::Exclam,
        x11::keysym::XK_quotedbl => KeyCode::Quotedbl,
        x11::keysym::XK_numbersign => KeyCode::NumberSign,
        x11::keysym::XK_dollar => KeyCode::Dollar,
        x11::keysym::XK_percent => KeyCode::Percent,
        x11::keysym::XK_ampersand => KeyCode::Ampersand,
        x11::keysym::XK_apostrophe => KeyCode::Apostrophe,
        x11::keysym::XK_quoteright => KeyCode::QuoteRight,
        x11::keysym::XK_parenleft => KeyCode::ParenLeft,
        x11::keysym::XK_parenright => KeyCode::ParenRight,
        x11::keysym::XK_asterisk => KeyCode::Asterisk,
        x11::keysym::XK_plus => KeyCode::Plus,
        x11::keysym::XK_comma => KeyCode::Comma,
        x11::keysym::XK_minus => KeyCode::Minus,
        x11::keysym::XK_period => KeyCode::Period,
        x11::keysym::XK_slash => KeyCode::Slash,
        x11::keysym::XK_colon => KeyCode::Colon,
        x11::keysym::XK_semicolon => KeyCode::Semicolon,
        x11::keysym::XK_less => KeyCode::Less,
        x11::keysym::XK_equal => KeyCode::Equal,
        x11::keysym::XK_greater => KeyCode::Greater,
        x11::keysym::XK_question => KeyCode::Question,
        x11::keysym::XK_at => KeyCode::At,
        x11::keysym::XK_bracketleft => KeyCode::BracketLeft,
        x11::keysym::XK_bracketright => KeyCode::BracketRight,
        x11::keysym::XK_backslash => KeyCode::Backslash,
        x11::keysym::XK_asciicircum => KeyCode::AsciiCircum,
        x11::keysym::XK_underscore => KeyCode::Underscore,
        x11::keysym::XK_grave => KeyCode::Grave,
        x11::keysym::XK_braceleft => KeyCode::BraceLeft,
        x11::keysym::XK_braceright => KeyCode::BraceRight,
        x11::keysym::XK_bar => KeyCode::Bar,
        //x11::keysym::XK_Tilde => KeyCode::Tilde,

        /* Keypad keys */
        x11::keysym::XK_KP_Space => KeyCode::KPSpace,
        x11::keysym::XK_KP_Tab => KeyCode::KPTab,
        x11::keysym::XK_KP_Enter => KeyCode::KPEnter,
        x11::keysym::XK_KP_Home => KeyCode::KPHome,
        x11::keysym::XK_KP_Left => KeyCode::KPLeft,
        x11::keysym::XK_KP_Up => KeyCode::KPUp,
        x11::keysym::XK_KP_Right => KeyCode::KPRight,
        x11::keysym::XK_KP_Down => KeyCode::KPDown,
        x11::keysym::XK_KP_Prior => KeyCode::KPPrior,
        x11::keysym::XK_KP_Page_Up => KeyCode::KPPageUp,
        x11::keysym::XK_KP_Next => KeyCode::KPNext,
        x11::keysym::XK_KP_Page_Down => KeyCode::KPPageDown,
        x11::keysym::XK_KP_End => KeyCode::KPEnd,
        x11::keysym::XK_KP_Begin => KeyCode::KPBegin,
        x11::keysym::XK_KP_Insert => KeyCode::KPInsert,
        x11::keysym::XK_KP_Delete => KeyCode::KPDelete,
        x11::keysym::XK_KP_Equal => KeyCode::KPEqual,
        x11::keysym::XK_KP_Multiply => KeyCode::KPMultiply,
        x11::keysym::XK_KP_Add => KeyCode::KPAdd,
        x11::keysym::XK_KP_Separator => KeyCode::KPSeparator,
        x11::keysym::XK_KP_Subtract => KeyCode::KPSubtract,
        x11::keysym::XK_KP_Decimal => KeyCode::KPDecimal,
        x11::keysym::XK_KP_Divide => KeyCode::KPDivide,

        x11::keysym::XK_KP_0 => KeyCode::KPDigit(0),
        x11::keysym::XK_KP_1 => KeyCode::KPDigit(1),
        x11::keysym::XK_KP_2 => KeyCode::KPDigit(2),
        x11::keysym::XK_KP_3 => KeyCode::KPDigit(3),
        x11::keysym::XK_KP_4 => KeyCode::KPDigit(4),
        x11::keysym::XK_KP_5 => KeyCode::KPDigit(5),
        x11::keysym::XK_KP_6 => KeyCode::KPDigit(6),
        x11::keysym::XK_KP_7 => KeyCode::KPDigit(7),
        x11::keysym::XK_KP_8 => KeyCode::KPDigit(8),
        x11::keysym::XK_KP_9 => KeyCode::KPDigit(9),

        _ => KeyCode::Unknown(keycode as u32, keystate as u32),
    }
}

pub(crate) fn convert_mouse(button: c_uint) -> MouseButton {
    match button {
        x11::xlib::Button1 => MouseButton::Left,
        x11::xlib::Button2 => MouseButton::Middle,
        x11::xlib::Button3 => MouseButton::Right,
        x11::xlib::Button4 => MouseButton::Special(0),
        x11::xlib::Button5 => MouseButton::Special(1),

        _ => MouseButton::Unknown(button as u32),
    }
}
